### PR TITLE
[Feature] - Remove the non-cloudauth option

### PR DESCRIPTION
**Pull request by lucasallan**

### CODE REVIEW

**Comment by th3wingman** [comment]
Do I have to update the public docs?

**Comment by th3wingman** [comment]
I'll need to update the quick start doc 😜

**Review by pedroandrade — APPROVED** [review]

**Comment by tresni** [comment]
So now I can't have a non-cloudauth'd tunnel?

**Comment by atoonk** [comment]
Correct @tresni  We're slowly moving away from non-cloudauth, to cloudauth only.

**Pull request merged**
